### PR TITLE
Add Microsoft Teams Bot

### PR DESCRIPTION
**Pull request by NithinSGowda**

### CODE REVIEW

**Review by KarenEfereyan — APPROVED** [review]
Looks good

**Comment by KarenEfereyan** [comment]
Thanks So much Nitin

**Comment by KarenEfereyan** [comment]
Thanks So much Nitin

**Comment by NithinSGowda** [comment]
Do me a favor of notifying me whenever you mention this extension on any  future blog post

**Comment by KarenEfereyan** [comment]
> Do me a favor of notifying me whenever you mention this extension on any future blog post

I'll be sure to do. You used the -s flag when committing to add the DCO check right?

**Comment by NithinSGowda** [comment]
> > Do me a favor of notifying me whenever you mention this extension on any future blog post
> 
> I'll be sure to do. You used the -s flag when committing to add the DCO check right?

I executed the these two commands :
git commit --amend --signoff
git push --force-with-lease origin add-Microsoft-Teams-Bot--Nithin-S

**Comment by KarenEfereyan** [comment]
Yes thank you so much. I forgot to add it to the contributing file so about 3 people had made contributions with checks not passing. I now remembered that yours passed. So i stopped to check. Then I realized that you signed your commits and that's when I remembered. Hahaha. You must be a long timer at open source contributions

**Pull request merged**
