### PR TITLE
prodeus

### PR DESCRIPTION
**Pull request by Shile01**
Signed-off-by: Khalid <horlarnshiley1@gmail.com>

### CODE REVIEW

**Review by KarenEfereyan — CHANGES_REQUESTED** [review]
Thank you Khalid. There are a few things you need to change before your commit gets merged. One, take the image and put it in the images folder. Then link from it there. Second,there seems to be a merge commit. Run this command to ensure all the new changes are fetched from the main stream repo
 1. git fetch origin master

**Comment by Shile01** [comment]
okay, I've tried fetching and pulling all the new changes but I still can't see anything on my editor plus I can't see any changes I make on my forked repo

**Comment by Shile01** [comment]
fixed the merge conflicts

**Comment by KarenEfereyan** [comment]
Okay hold on. Lets try to figure it out togethee

**Comment by KarenEfereyan** [comment]
Finally! @Shile01 I'm proud of you

**Comment by Shile01** [comment]
wish I could use a smiley here...Thanks ma

**Pull request merged**
