### PR TITLE
add visual-inspector

### PR DESCRIPTION
**Pull request by PaimoEmmanuel**
Signed-off-by: EMMANUEL PAIMO <paimoemmanuel2016@gmail.com>

### CODE REVIEW

**Comment by KarenEfereyan** [comment]
Thanks for your contribution @PaimoEmmanuel. Have you made the 4 required PRs for hacktoberfest. If not, feel free to add more extensions. You are helping us all. Also, remember to kindly leave a star and tell others.

**Comment by PaimoEmmanuel** [comment]
Hi Karen, thank you.
However, Hacktoberfest is reading this as an ineligible repo

You might need to see this

Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by KarenEfereyan** [comment]
> Hi Karen, thank you.
> However, Hacktoberfest is reading this as an ineligible repo
> 
> You might need to see this
> 
> Ineligible Repository
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

Ohh that's weird. Hold on, let me add a hacktoberfest label to your PR. It should be fine then

**Comment by PaimoEmmanuel** [comment]
The tag is  "hacktoberfest-accepted" but you can also just  "hacktoberfest" as a tag in the about of the repository so you don't have to do it for every PR

**Comment by KarenEfereyan** [comment]
> The tag is "hacktoberfest-accepted" but you can also just "hacktoberfest" as a topic in the about of the repository so you don't have to do it for every PR

Will do that right now. Thanks!

**Comment by PaimoEmmanuel** [comment]
Thanks, Karen.

**Pull request merged**
