### PR TITLE
Fixed/Add Snippet.md placeholder image

### PR DESCRIPTION
**Pull request by mraheelkhan**
Signed-off-by: Raheel Khan <irahilkhan@gmail.com>

### CODE REVIEW

**Review by KarenEfereyan — COMMENTED** [review]
@mraheelkhan you didnt add the links for downloading on Mozilla and chrome

**Comment by mraheelkhan** [comment]
@KarenEfereyan I have modified the Snippet.md file, there is no need to add links for downloading.

**Comment by mraheelkhan** [comment]
Please look into this PR.

**Comment by KarenEfereyan** [comment]
Thanks a lot for this @mraheelkhan . Merging right now....

**Pull request merged**
