### PR TITLE
Snippet addition

### PR DESCRIPTION
**Pull request by capturemathan**
Fixes #29

### CODE REVIEW

**Review by KarenEfereyan — COMMENTED** [review]
This is great @capturemathan . I can't figure out why there is a merge conflict again. Uhmm Let's see

**Comment by capturemathan** [comment]
> This is great @capturemathan . I can't figure out why there is a merge conflict again. Uhmm Let's see

I think you merged the earlier PR's rather than the older PR's. Because all the checks from my side have passed 😉

**Comment by KarenEfereyan** [comment]
What do we do now? We just have to resolve the conflicts, you know? Maybe try fetching the latest updates and until then, I won't merge any other PR

**Comment by capturemathan** [comment]
> What do we do now? We just have to resolve the conflicts, you know? Maybe try fetching the latest updates and until then, I won't merge any other PR

I have resolved the conflict you can now merge 💯

**Comment by KarenEfereyan** [comment]
Yippie. Thank you so much.

**Pull request merged**
