### PR TITLE
Add webmaker hikwamehluli

### PR DESCRIPTION
**Pull request by HikwaMehluli**

### CODE REVIEW

**Comment by KarenEfereyan** [comment]
@HikwaMehluli  thanks so much for your contribution. Could you please follow the guidelines here to get your checks passed? It was my fault. I have updated the contributing file to reflext that change. Thank you 
https://github.com/KarenEfereyan/extensions-4-every-developer/pull/5/checks?check_run_id=1148327860

**Comment by HikwaMehluli** [comment]
> @HikwaMehluli thanks so much for your contribution. Could you please follow the guidelines here to get your checks passed? It was my fault. I have updated the contributing file to reflext that change. Thank you
> https://github.com/KarenEfereyan/extensions-4-every-developer/pull/5/checks?check_run_id=1148327860

Thanks, I think all checks have worked now.

**Comment by KarenEfereyan** [comment]
thanks so much @HikwaMehluli . There seems to be a merge conflict. Could you kindly take a look? I'm sorry for the inconveniences

**Comment by HikwaMehluli** [comment]
> thanks so much @HikwaMehluli . There seems to be a merge conflict. Could you kindly take a look? I'm sorry for the inconveniences

I have resolved the merge conflift, thank you

**Review by KarenEfereyan — APPROVED** [review]

**Comment by KarenEfereyan** [comment]
Thank you so much @HikwaMehluli I appreciate this. Please remember to keep on making additions of useful extensions you find. And if there's anything I can do to make this project even better be sure to tell me.

**Pull request merged**
