### PR TITLE
added_uBlock

### PR DESCRIPTION
**Pull request by jomefavourite**

### CODE REVIEW

**Review by KarenEfereyan — APPROVED** [review]
Thanks Jome

**Comment by KarenEfereyan** [comment]
@jomefavourite could you please follow the directions here to get your checks to pass? https://github.com/KarenEfereyan/extensions-4-every-developer/pull/3/checks

**Comment by jomefavourite** [comment]
I'm I to sign off

**Comment by KarenEfereyan** [comment]
Yes..you should..

**Comment by KarenEfereyan** [comment]
@jomefavourite the checks still failed. But no worries, for next time, kindly be sure to sign off your commits. Thanks for contributing

**Comment by jomefavourite** [comment]
I did sign off this time, I dont know why it didn't go through.

**Comment by KarenEfereyan** [comment]
I have no idea too but i merged already so no worries

**Pull request merged**
